### ISSUE TITLE
missing dependencies 

### ISSUE THREAD

**Issue by Drodofsky** [Brotcrunsher/BrotBoxEngine#2]
Please remove `-lportaudio_static`. I cannot find a good way to install it on Manjaro or Fedora. Only the dynamically linked library `-lportaudio` is in the package manager. Not all dependencies are checked in the Cmake script.

**Comment by Brotcrunsher** [comment]
Hi! Portaudio is built from source on Linux. See https://github.com/Brotcrunsher/BrotBoxEngine/blob/master/.travis.yml how this can be done.
