### ISSUE TITLE
NoSuchKeyCodeException is thrown when pressing Fn Key

### ISSUE THREAD

**Issue by mariusheil** [Brotcrunsher/BrotBoxEngine#4]
Hello,

I am developing a project that uses the BrotBoxEngine to do real-time rendering of a simulated environment. I have now run into an issue that causes the engine to fail with a NoSuchKeyCodeException once the "Fn" key on the keyboard is pressed. To provide some reference, I am developing on a Lenovo Notebook and have my Fn and Strg Keys swapped on the keyboard, but I do not know if this makes a difference.

Here is a screenshot of where the exception is thrown. I was previously using BBE 0.1.7 and have now updated to 0.1.8 for testing if the bug is still present.

![image](https://user-images.githubusercontent.com/5893428/182840093-fe63e215-ae73-448c-8ebc-a54604ac50d9.png)

The debugger will fail at this point but it seems to be because the exception is thrown:
![image](https://user-images.githubusercontent.com/5893428/182840251-edc40d6e-c461-41f0-b7e5-3e298241c2d4.png)

These are the values that are passed to the above method:
![image](https://user-images.githubusercontent.com/5893428/182840384-33503bb1-47ee-492c-bb0b-7075d2319062.png)

Thank you,
Marius Heil

.............................

As a workaround, I was able to include:
```
void bbe::INTERNAL_keyCallback(GLFWwindow * window, int keyCode, int scanCode, int action, int mods)
{
	if (keyCode == 0xFFFFFFFFUL) return;
```
in Window.cpp but this could have a number of side affects, but it looks like the keycode/scancode functionality is a bit of a mess between different vendors.

**Comment by Brotcrunsher** [comment]
Hi Marius, sorry for the late reply.

That is indeed very surprising behavior by GLFW (that's the lib that gives us the key events). I was looking through a few other code bases and realized that most don't seem to expect this. For example the (admittingly outdated) version of [Dear ImGUI](https://github.com/ocornut/imgui) that the BBE uses wasn't prepared for this as well.

Your proposed workaround is technically quite close to the fix. It could only lead to problems on other architectures that don't have `sizeof(int)==4` and was UB before C++20. The correct fix (or so I hope) is to check for `GLFW_KEY_UNKNOWN`. I just commited that to the repository. 

Thank you very much for reporting this. It would be great if you could briefly check if this indeed fixed your issue.

**Comment by mariusheil** [comment]
Hello,

thank you and yes, this indeed fixed the issue. :-)

Marius
