### ISSUE TITLE
Debug break and Validation Error by trying to run a ExampleProject

### ISSUE THREAD

**Issue by Mankimann** [Brotcrunsher/BrotBoxEngine#5]
`Validation Error: [ VUID-vkCmdDrawIndexed-blendEnable-04727 ] Object 0: handle = 0x625f640000000058, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x8a06751e | vkCmdDrawIndexed: Image view's format features of the color attachment (0) of the active subpass do not contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT bit, but active pipeline's pAttachments[0].blendEnable is not VK_FALSE. The Vulkan spec states: If rasterization is not disabled in the bound graphics pipeline, then for each color attachment in the subpass, if the corresponding image view's format features do not contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT, then the blendEnable member of the corresponding element of the pAttachments member of pColorBlendState must be VK_FALSE (https://vulkan.lunarg.com/doc/view/1.3.239.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-blendEnable-04727)`

`Starting Game: Neural Rocket!
Starting math
Creating window
Init render manager
Vulkan Manager: init instance
loader_get_json: Failed to open JSON file E:\Epic Games\Launcher\Portal\Extras\Overlay\EOSOverlayVkLayer-Win32.json 

debugBreak() was triggered! C:\Users\mankn\Desktop\BrotBoxEngine-0.2.0\BrotBoxEngine-0.2.0\BrotBoxEngine\Vulkan\VulkanInstance.cpp(45)`

**Comment by Mankimann** [comment]
I changed the api version from 1.0 to 1.1 and yeah it works for me

**Comment by Brotcrunsher** [comment]
Hi! The Vulkan Renderer is currently in a somewhat "discontinued" state and it's quite possible that it will be removed in the future. The BBE is using OpenGL by now as its main renderer.
